### ISSUE TITLE
Immersive Engineering

### ISSUE THREAD

**Issue by Ezelberoth** [Szewek/Minecraft-Flux#1]
I recently tried to install this, but I don't use Immersive Engineering. Every time I load the game with this mod, but not IE, I get this error:

http://pastebin.com/kRh6gtwe

If I load WITH IE, it does not produce the error, but I cannot use IE, as it causes horrid lag for me with my other mods. If this mod requires IE, it should list that as a requirement, not a compatibility.

**Comment by szeweq** [comment]
It's an error with the builds. Gradle doesn't include APIs needed for Minecraft-Flux to work (if you remove all RF energy mods then you should see very similar error, but with CoFH API).

The fix will be in the next release.
