### ISSUE TITLE
TechReborn incompatibility 

### ISSUE THREAD

**Issue by modmuss50** [Szewek/Minecraft-Flux#11]
Hello, I am the developer of TechReborn and I had an issue opened about some of my machines not processing some materials. After a LOT of effort I tracked it down to your mod.

Using the following versions of my mods: 

RebornCore-1.11.2-2.13.4.37
&
TechReborn-1.11.2-2.1.6.76

Our compressor will compress carbon mesh into plates just fine: 
<img width="1680" alt="screen shot 2017-02-23 at 23 13 29" src="https://cloud.githubusercontent.com/assets/4324090/23283967/c498c746-fa20-11e6-9538-4b546d90db83.png">

But when mcflux-2.4.2 is brought into the mix the machine no longer processes. Im not familiar with
what your mod does but it should not be breaking our machines. Feel free to ask any questions and I  look forward to getting to the bottom of the issue.

Related issue on our tracker: https://github.com/TechReborn/TechReborn/issues/982

**Comment by epharian** [comment]
As a follow-up, I'm the user that originally opened the ticket for tech reborn, and helped Modmuss track this down (or rather, provided enough information that it could be found).

Look forward to seeing this resolved.

**Comment by szeweq** [comment]
@modmuss50 Do TechReborn machines use ItemStack matching with NBT? It's important because Minecraft-Flux adds a capability for every ItemStack and saves data in `mcflux:wrapper` tag (even null data). This bug could be solved by using some more strict NBT check.

**Comment by modmuss50** [comment]
That could be the cause yes.

**Comment by modmuss50** [comment]
It's a bit more than appearance as it stops our machines from functioning
