### ISSUE TITLE
Crash w/ Roots 2 1.10.2

### ISSUE THREAD

**Issue by WenXin20** [Szewek/Minecraft-Flux#16]
[Roots 2](https://minecraft.curseforge.com/projects/roots/files/2401111) v0.015
MC Flux v1.6.1
Forge 2254-1.10.2
I got this crash when I loaded a previously generated world with Roots 2, which was recently backported to 1.10.2.
[Crash Report](https://pastebin.com/CG7tKCad)

**Comment by MinecraftArchive** [comment]
Roots 2 is 1.11.2 only CLOSED

**Comment by WenXin20** [comment]
There was a version back ported to 1.10.2....

**Comment by WenXin20** [comment]
Never mind, looks like that was an April fools version, and is now removed.
