### ISSUE TITLE
Request - Forward 1.11.2 fixes to 1.10.2 because Tinkers Is not completely 1.11.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Szewek/Minecraft-Flux#17]
Hey so I was wondering I love the concept of this mod but judging from your releases you are no longer keeping up the 1.10.2 release would you be willing to reconsider? There are quite a few gems left in 1.10.2 it would mean a lot to me if you could even if its far less often like every 10 1.11.2 releases or something.

**Comment by CrabDeSass** [comment]
Don't hold your breath. I'm not familiar with the modder so for all I know they could be happy to keep things up in shape when brought to their attention, as long as you don't harass them to high hell with "UPDATE PLS?!" every day. 

But welcome to the downfall of Minecraft's modding community post-1.6.5. Too many and too frequent versions, with "main versions, _plural_" becoming a thing when most folks used to use and mod a single version at a time outside of transitioning. Those who can and choose to jump to the newest version to mod for when it comes out, refuse to/slowly stop modding for any prior version regardless of how many people still use their mod and the older version, expecting everyone to follow or do without, and people are left to chose between abandoning a few mods playing follow the leader or many great mods. And those who can't update their mods as fast get left in the dust, either they lose interest/motivation from the constant flood of demands to update every few months, or they feel overwhelmed, or real life takes priority. 

Rest in Pieces Metallurgy 3, the original Tinker's Construct, and many more good works.
