### ISSUE TITLE
Tinkers Construct Casting Table bug

### ISSUE THREAD

**Issue by piedpipr314** [Szewek/Minecraft-Flux#21]
This mod together with tinkers' causes the casting table to not pour molds.  Confirmed with Mantle, Tinkers and this mod only in a small pack.

**Comment by Debonairesnake6** [comment]
Also, won't allow you to melt slime in the tinker's smeltery

**Comment by CrabDeSass** [comment]
I'm going to presume this is the same issue as what's causing the Tinker's Stencil Table to not produce patterns in a new game, since this is the only mod I've added since to cause this, and the issue goes away with removing it.
