### ISSUE TITLE
Conflict with RefinedStorage v 1.3.5, specifically solders

### ISSUE THREAD

**Issue by SierraNine** [Szewek/Minecraft-Flux#6]
Minecraft - 1.11.2
refinedstorage-1.3.5
mcflux-2.0.1  vs mcflux-2.0.0-b7

Updated mcflux from 2.0.0-b7 to 2.0.1. No other changes.

Refined Storage Solders would no longer accept items in top or bottom slot.

Reverted to mcflux-2.0.0-b7, no other changes, and Refine Storage again worked as expected.

**Comment by SierraNine** [comment]
Additional info:
forge-1.11.2-13.20.0.2226

Exact same results stand alone and client-server.

**Comment by SierraNine** [comment]
Same results with mcflux-2.0.2.

Refine Storage Solders fail when upgraded to mcflux-2.0.2. No other changes made.

Reverting to mcflux-2.0.0-b7 restores normal behaviors.

**Comment by szeweq** [comment]
Did you receive some warnings or errors like "NBT data cannot be saved or read" or something similar? If you do, please send these logs (via Pastebin or Gist). I can't reproduce that problem so I need more information about it.

**Comment by SierraNine** [comment]
Negative, no log message of any kind, standalone nor client-server. 

The selected items simply will not click into their respective top or bottom slots in the RS Solder. The middle slot behaves normally. I have tried a number of different items, both RS specific and Minecraft vanilla that are valid recipe items. The same exact test world ( and actual game worlds ) behave as expected when mcflux-2.0.0-b7 is swapped back in the place of mcflux-2.0.1+ and the world restarted. 

I'm running a large, custom private mod pack with over 120 mods. There may well be an unfortunate  synergy taking place. I am going to pull all mods updated in the past two weeks and test to see if another mod is the actual issue. This will take several hours and I won't begin until after evening my time. I'll advise my results.

**Comment by SierraNine** [comment]
I tested with the following mods:
ActuallyAdditions-1.11.2-r99
CommonCapabilities-1.11.2-1.3.0
ConvenientAdditions-1.0.17-build27
CyclopsCore-1.11.2-0.9.1
EverlastingAbilities-1.11.2-1.2.4
ExponentialPower-1.1.1
Growable Cells-0.3.3
IvToolkit-1.3.2-1.10
RecurrentComplex-1.2.8
Supply Drop-1.11.2-1.0.1
UtilityWorlds-1.11.2_1.1.0
ViesCraft-1.11.2-4.11.0
environmentaltech-1.11.2-0.11.0d
extrautils2-1.11.2-1.2.0
justenoughbuttons-1.11.2-1.4.1
llibrary-1.7.4-1.11
mcjtylib-1.1x-2.3.5
multistorage-1.11.0-1.3.4
pmdumper-1.11.2-1.5.1
rftools-1.1x-5.82
shetiphiancore-1.11.0-3.4.2
simplegenerators-1.11.2-0.11.0a
teslafied-1.11-1.1.0
thedragonlib-1.11.2-2.1.0
theoneprobe-1.1x-1.4.1
valkyrielib-1.11.2-0.11.0c
zz-backpacks 1.11.2 - 3.1.7

I removed all of the mods updated in the past ten days, listed above, and none has any effect on mcflux v2.0.1+ and Refined Storage.

I understand you can not replicate this issue. Been there, done that, still have the scars...

I will continue to test my private mod pack as new versions  are released. This is a promising mod and I would like to use it if I can resolve this issue.

**Comment by SierraNine** [comment]
Updated to mcflux 2.0.5, no change.

Updated: 
CommonCapabilities-1.11.2-1.3.0 to CommonCapabilities-1.11.2-1.3.1
CyclopsCore-1.11.2-0.9.1 to CyclopsCore-1.11.2-0.9.2

and built RefinedStorage 1.4 from the source.

And the problem has been resolved. 

Obviously, it was a slight conflict amongst one of those three mods and mcflux.

Please close this issue.

**Comment by kreezxil** [comment]
Confirmed here, no console messges of any kind. TAke out your mod and the pack works.
