### ISSUE TITLE
1.11.2-2.0.2 crashes dedicated Forge 1.11.2 build 2226  on player connect

### ISSUE THREAD

**Issue by kreezxil** [Szewek/Minecraft-Flux#8]
crash report:
https://gist.github.com/30bf18101449e816b763337b66ce04cd

fml server latest:
https://gist.github.com/3c4ce5fac78c9c26df66763b6663a6af

**Comment by szeweq** [comment]
This (client-side method on dedicated server) will be fixed in 2.0.4 release (very soon).

**Comment by szeweq** [comment]
It's now fixed in 2.0.4.
